version: '3'

services:
  redis:
    image: redis
    network_mode: host
  vf:
    build:
      context: "."
      dockerfile: Dockerfile.dev
    network_mode: host
    volumes:
      - $PWD:/appdata
      - /secrets:/secrets
  idptest:
    image: ghcr.io/dexidp/dex:latest
    network_mode: host
    volumes:
      - ./test/e2e/configs/dex.yaml:/etc/dex/config.yaml
    command: ["dex", "serve", "/etc/dex/config.yaml"]