FROM caddy:2.7-alpine AS caddy

FROM node:slim
RUN apt update && apt upgrade -y && apt install -y ca-certificates supervisor
COPY --from=caddy /usr/bin/caddy /usr/bin/caddy
COPY docker/supervisord-dev.conf /etc/supervisord.conf
COPY caddyfile-blank.json /etc/caddy.json
WORKDIR /appdata

ENTRYPOINT ["/usr/bin/supervisord", "-n", "-c", "/etc/supervisord.conf"]
