FROM caddy:2.7-alpine AS caddy

FROM node
COPY --from=caddy /usr/bin/caddy /usr/bin/caddy
COPY caddyfile-blank.json /etc/caddy.json
COPY entrypoint.sh /entrypoint.sh
WORKDIR /appdata

ENTRYPOINT /entrypoint.sh