version: '3'

services:
  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'
  frontend:
    build:
      context: "."
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - $PWD:/appdata
    environment:
      REDIS_HOST: redis