name: End-to-End Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Run end-to-end tests
      run: make test-e2e

    - name: Archive E2E Test Output
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: e2e-test-screenshots
        path: |
          test/e2e/output/*